LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := KernelAdiutor-legacy
LOCAL_SRC_FILES := KernelAdiutor.apk
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH  := $(TARGET_OUT_APPS)
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)
